[libraries]
assertj = "org.assertj:assertj-core:3.12.0"
avro = "org.apache.avro:avro:1.10.2"
calciteAvatica = "org.apache.calcite.avatica:avatica:1.22.0"
calciteCore = "org.apache.calcite:calcite-core:1.34.0"
flinkClients = "org.apache.flink:flink-clients:1.17.0"
flinkConnectorBase = "org.apache.flink:flink-connector-base:1.17.0"
flinkCore = "org.apache.flink:flink-core:1.17.0"
flinkStreamingJava = "org.apache.flink:flink-streaming-java:1.17.0"
flinkTableApiJava = "org.apache.flink:flink-table-api-java:1.17.0"
flinkTableApiJavaBridge = "org.apache.flink:flink-table-api-java-bridge:1.17.0"
flinkTableCommon = "org.apache.flink:flink-table-common:1.17.0"
flinkTablePlanner = "org.apache.flink:flink-table-planner_2.12:1.17.0"
flinkTableRuntime = "org.apache.flink:flink-table-runtime:1.17.0"
flinkConnectorKafka = "org.apache.flink:flink-connector-kafka:1.17.0"
gson = "com.google.code.gson:gson:2.8.6"
jackson = "com.fasterxml.jackson.core:jackson-core:2.13.2"
jacksonYaml = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.13.2"
javaxAnnotationApi = "javax.annotation:javax.annotation-api:1.3.2"
junit = "junit:junit:4.12"
kafkaClients = "org.apache.kafka:kafka-clients:3.1.1"
kubernetesClient = "io.kubernetes:client-java:16.0.2"
kubernetesExtendedClient = "io.kubernetes:client-java-extended:16.0.2"
slf4jLog4j = "org.slf4j:slf4j-log4j12:1.7.25"
sqlline = "sqlline:sqlline:1.12.0"
