apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flinksqljobs.hoptimator.linkedin.com
spec:
  group: hoptimator.linkedin.com
  names:
    kind: FlinkSqlJob
    listKind: FlinkSqlJobList
    plural: flinksqljobs
    singular: flinksqljob
    shortNames:
    - fsj
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Flink SQL job
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              description: Flink SQL job spec.
              type: object
              properties:
                sql:
                  description: Flink SQL statements.
                  type: array
                  items:
                    type: string
              required:
              - sql
            status:
              description: Current state of the Flink SQL job.
              type: object
              properties:
                ready:
                  description: Whether the requested job has been created.
                  type: boolean
                message:
                  description: Error or success message, for information only.
                  type: string
      subresources:
        status: {}
